Repository OData/WebApi, pull requests merged in 2021-05, with the labels that each got.

#2491 Make the reflection more robust
  src/Microsoft.AspNet.OData.Shared/DefaultContainerBuilder.cs
Labels: Extra Small

#2492 fix issue #2489: ClrTypeCache has memory leak
  src/Microsoft.AspNet.OData.Shared/Formatter/ClrTypeCache.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/ClrTypeCacheTest.cs
Labels: Small

#2497 Upgrade ODL version to v7.9.0
  samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
  samples/AspNetODataSample.Web/packages.config
  src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
  src/Microsoft.AspNet.OData/packages.config
  src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Validators/FilterQueryValidatorTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
  test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj
Labels: Medium
