Repository OData/WebApi, pull requests merged in 2021-10, with the labels that each got.

#2578 Fix deltacomplex type
  src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs
  src/Microsoft.AspNet.OData.Shared/Formatter/Deserialization/ODataResourceDeserializer.cs
  src/Microsoft.AspNet.OData/GlobalSuppressions.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ComplexTypeInheritance/ComplexTypeInheritanceTests.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Formatter/DeltaTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/Conventions/ODataConventionModelBuilderTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/TestModels/InheritanceModels.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/InheritanceTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore3x.OData.PublicApi.bsl
Labels: Large

#2575 Fixing Patching Complex type when using one derived type over another
  src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs
  src/Microsoft.AspNet.OData.Shared/Formatter/Deserialization/ODataResourceDeserializer.cs
  src/Microsoft.AspNet.OData/GlobalSuppressions.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ComplexTypeInheritance/ComplexTypeInheritanceTests.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Formatter/DeltaTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/Conventions/ODataConventionModelBuilderTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/TestModels/InheritanceModels.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/InheritanceTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore3x.OData.PublicApi.bsl
Labels: Large

#2544 Fix to ignore Unmapped properties in Delta<T>
  src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/DeltaTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/TestCommon/Models/TestDataModels.cs
Labels: Small

#2339 Ensure that untyped values escaped in ODL are unescaped in OData WebApi during deserialization
  src/Microsoft.AspNet.OData.Shared/Formatter/Deserialization/DeserializationHelpers.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Deserialization/DeserializationHelpersTest.cs
Labels: Ready for review

#2582 Enable Auto expand on complex type
  src/Microsoft.AspNet.OData.Shared/Common/SRResources.Designer.cs
  src/Microsoft.AspNet.OData.Shared/Common/SRResources.resx
  src/Microsoft.AspNet.OData.Shared/EnableQueryAttribute.cs
  src/Microsoft.AspNet.OData.Shared/Formatter/EdmLibHelpers.cs
  src/Microsoft.AspNet.OData.Shared/Microsoft.AspNet.OData.Shared.projitems
  src/Microsoft.AspNet.OData.Shared/Query/AutoSelectExpandHelper.cs
  src/Microsoft.AspNet.OData.Shared/Query/ExpandModelPath.cs
  src/Microsoft.AspNet.OData.Shared/Query/ODataQueryOptions.cs
  src/Microsoft.AspNet.OData.Shared/Query/SelectExpandQueryOption.cs
  src/Microsoft.AspNet.OData.Shared/Query/SelectModelPath.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/AutoExpand/AutoExpandNavigationOnComplexTests.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Deserialization/DeserializationHelpersTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Microsoft.AspNet.OData.Test.Shared.projitems
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/EnableQueryAttributeTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/ExpandModelPathTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/SelectModelPathTests.cs
Labels: Extra Large

#2588 Fix auto expand null-reference
  src/Microsoft.AspNet.OData.Shared/Query/SelectExpandQueryOption.cs
Labels: Extra Small
