Repository OData/WebApi, pull requests merged in 2021-04, with the labels that each got.

#2426 Multiple level of OrderBy
  src/Microsoft.AspNet.OData.Shared/Query/Expressions/SelectExpandBinder.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Expressions/SelectExpandBinderTest.cs
Labels: Ready for review

#2457 Filter is not working with date function
  src/Microsoft.AspNet.OData.Shared/Query/Expressions/ExpressionBinderBase.cs
  src/Microsoft.AspNet.OData.Shared/Query/Expressions/FilterBinder.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Expressions/FilterBinderTests.cs
Labels: Medium

#2482 Revert "inconsistencies in query options when_returnscollection is us…
  src/Microsoft.AspNet.OData.Shared/Builder/FunctionConfiguration.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Formatter/ODataFeedSerializeWithoutNavigationSourceTests.cs
Labels: Extra Small
