Repository OData/WebApi, pull requests merged in 2021-06, with the labels that each got.

#2506 Feature/new add support for odata bind
  src/Microsoft.AspNet.OData.Shared/Formatter/Deserialization/ODataEntityReferenceLinkBase.cs
  src/Microsoft.AspNet.OData.Shared/Formatter/Deserialization/ODataNestedResourceInfoWrapper.cs
  src/Microsoft.AspNet.OData.Shared/Formatter/Deserialization/ODataResourceDeserializer.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Formatter/ODataEntityReferenceLinkE2ETests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/ODataEntityReferenceLinkTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Microsoft.AspNet.OData.Test.Shared.projitems
Labels: Large

#2421 Add support for $this
  src/Microsoft.AspNet.OData.Shared/Query/Expressions/FilterBinder.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Expressions/SelectExpandBinderTest.cs
Labels: Extra Small

#2494 Fix API Explorer usage with OData.
  src/Microsoft.AspNetCore.OData/Formatter/ODataInputFormatter.cs
  src/Microsoft.AspNetCore.OData/Formatter/ODataOutputFormatter.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/ODataMediaTypeFormattersTests.cs
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore3x.OData.PublicApi.bsl
Labels: Extra Small, Ready for review

#2487 Tests using TimeZoneInfo fail due to race conditons
  src/Microsoft.AspNet.OData/GlobalSuppressions.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/DateAndTimeOfDay/DateAndTimeOfDayTest.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/DateTimeSupport/DateTimeTest.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ModelBoundQuerySettings/PageAttributeTest/SkipTokenTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/DateTimeTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/DefaultODataETagHandlerTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Deserialization/CollectionDeserializationHelpersTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Deserialization/DeserializationHelpersTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Deserialization/ODataPrimitiveDeserializerTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/EdmPrimitiveHelpersTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/ODataModelBinderProviderTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Serialization/CollectionTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Serialization/ODataPrimitiveSerializerTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/HttpConfigurationExtensionsTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Expressions/FilterBinderTests.cs
Labels: Extra Small, Ready for review
