Repository OData/WebApi, pull requests merged in 2021-07, with the labels that each got.

#2515 Enable constant parameterization in DateTime constants
  src/Microsoft.AspNet.OData.Shared/Query/Expressions/ExpressionBinderBase.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Expressions/FilterBinderTests.cs
Labels: Extra Small, Ready for review

#2521 Add support for dollar count segment in filter
  src/Microsoft.AspNet.OData.Shared/Query/Expressions/FilterBinder.cs
  src/Microsoft.AspNet.OData.Shared/Query/ParameterAliasNodeTranslator.cs
  src/Microsoft.AspNet.OData.Shared/Query/Validators/FilterQueryValidator.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Expressions/FilterBinderTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore3x.OData.PublicApi.bsl
Labels: Extra Small, Ready for review

#2525 Fixed Enum try parse issue. This closes #2518
  src/Microsoft.AspNet.OData.Shared/Formatter/ODataModelBinderConverter.cs
  src/Microsoft.AspNet.OData.Shared/Query/Expressions/ExpressionBinderBase.cs
Labels: Extra Small

#2512 Fix behaviour on status code requests.
  src/Microsoft.AspNetCore.OData/EnableQueryAttribute.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/EnableQueryAttributeTest.cs
Labels: Small

#2530 Fix bug in Filter Any within Expand
  src/Microsoft.AspNet.OData.Shared/Query/Expressions/FilterBinder.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Expressions/SelectExpandBinderTest.cs
Labels: Extra Small
