Repository OData/WebApi, pull requests merged in 2021-08, with the labels that each got.

#2456 Built-in support for deeply nested paths
  src/Microsoft.AspNet.OData.Shared/EnableQueryAttribute.cs
  src/Microsoft.AspNet.OData.Shared/ExpressionHelperMethods.cs
  src/Microsoft.AspNet.OData.Shared/ExpressionHelpers.cs
  src/Microsoft.AspNet.OData.Shared/Interfaces/IWebApiActionMap.cs
  src/Microsoft.AspNet.OData.Shared/Microsoft.AspNet.OData.Shared.projitems
  src/Microsoft.AspNet.OData.Shared/Query/ODataPathQueryBuilder.cs
  src/Microsoft.AspNet.OData.Shared/QueryHelpers.cs
  src/Microsoft.AspNet.OData.Shared/Routing/Conventions/NestedPathsRoutingConvention.cs
  src/Microsoft.AspNet.OData/Adapters/WebApiActionMap.cs
  src/Microsoft.AspNetCore.OData/Adapters/WebApiActionDescriptor.cs
  src/Microsoft.AspNetCore.OData/Adapters/WebApiActionMap.cs
  src/Microsoft.AspNetCore.OData/EnableNestedPathsAttribute.cs
  src/Microsoft.AspNetCore.OData/Routing/Conventions/NestedPathsRoutingConvention.cs
  src/Microsoft.AspNetCore.OData/Routing/Conventions/ODataRoutingConventions.cs
  src/Microsoft.AspNetCore.OData/Routing/ODataActionSelector.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/NestedPaths/NestedPathEFTests.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/NestedPaths/NestedPathsTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/EnableNestedPathsTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Microsoft.AspNet.OData.Test.Shared.projitems
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/EnableQueryAttributeTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/ODataPathQueryBuilderTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Routing/Conventions/NestedPathsRoutingConventionTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Routing/ODataRoutingModel.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Routing/ODataRoutingTest.cs
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore3x.OData.PublicApi.bsl
Labels: Extra Large, docs needed

#2541 Update version to 7.5.9
  tools/WebStack.versions.settings.targets
Labels: Ready for review, Extra Small

#2529 Migrate to Dotnet foundation.
  configs/filelist.txt
  images/odata.png
  pipelines/azure_pipelines.yml
  pipelines/azure_pipelines_nightly.yml
  pipelines/common.yml
  src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.Nightly.nuspec
  src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.Release.nuspec
  src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.Nightly.nuspec
  src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.Release.nuspec
  src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
  tools/GetNugetPackageMetadata.proj
Labels: Large

#2548 Update copyrights on non-source files
  .github/CONTRIBUTION.md
  License.txt
  README.md
  src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.Nightly.nuspec
  src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.Release.nuspec
  src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.Nightly.nuspec
  src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.Release.nuspec
Labels: Extra Small

#2483 Delta does not allow UpdatableProperties to be changed
  src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/DeltaTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/ODataModelBinderProviderTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/PublicApi/PublicApiTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore3x.OData.PublicApi.bsl
Labels: Ready for review, Large
