Repository OData/WebApi, pull requests merged in 2022-08, with the labels that each got.

#2698 Update release version to 7.5.16 and ODL version to 7.12.2
  samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
  src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
  src/Microsoft.AspNet.OData/packages.config
  src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
  test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
  test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj
  tools/WebStack.versions.settings.targets
Labels: Medium

#2699 Add virtual method for complex property serialization
  src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/ODataResourceSerializer.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Serialization/ODataResourceSerializerTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore3x.OData.PublicApi.bsl
Labels: Small

#2694 Bump Microsoft.OWin to 4.0 and Microsoft.AspNetCore.Mvc.Core 2.0.1
  src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/QueryComposition/ComplextTypeCollectionTests.cs
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj
Labels: Extra Small
