Repository OData/WebApi, pull requests merged in 2022-11, with the labels that each got.

#2720 update the version 7.6.2 and update the Core dependency version to 2.0.1
  tools/WebStack.versions.settings.targets
Labels: Extra Small

#2718 Upgrade Kestrel to 2.2.0
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/App.config
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
Labels: Large

#2725 Change VmImage from latest to 2019 to finish the build pipeline build
  pipelines/azure_pipelines.yml
  pipelines/azure_pipelines_nightly.yml
Labels: Extra Small

#2722 Fix issue for nested next page link with singleton containment navigation property
  src/Microsoft.AspNet.OData.Shared/Builder/LinkGenerationHelpers.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Singleton/MonstersIncController.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Singleton/ODataClient.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Singleton/SingletonDataModel.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Singleton/SingletonEdmModel.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Singleton/SingletonTest.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Singleton/UmbrellaController.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/LinkGenerationHelpersTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/TestModels/MyOrder.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/TestModels/OrderItem.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Builder/TestModels/OrderItemDetail.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Microsoft.AspNet.OData.Test.Shared.projitems
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/TestCommon/CustomersModelWithInheritance.cs
Labels: Large

#2727 Updated out-of-date .NET Foundation Code of Conduct Link
  README.md
Labels: Extra Small

#2729 Fix serialization issue affecting nested complex property
  src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/ODataResourceSerializer.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Aggregation/AggregationController.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Aggregation/AggregationDataModel.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Aggregation/AggregationTests.cs
Labels: Small
