Repository OData/WebApi, pull requests merged in 2022-02, with the labels that each got.

#2618 New PR for Serializers for Bulk Operation with Updated ContextPath
  src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs
  src/Microsoft.AspNet.OData.Shared/EdmChangedObjectCollection.cs
  src/Microsoft.AspNet.OData.Shared/EdmEntityObject.cs
  src/Microsoft.AspNet.OData.Shared/Formatter/Deserialization/ODataResourceDeserializer.cs
  src/Microsoft.AspNet.OData.Shared/IDeltaSetItem.cs
  src/Microsoft.AspNet.OData.Shared/NavigationPath.cs
  src/Microsoft.AspNet.OData.Shared/ODataAPIHandlerFactory.cs
  src/Microsoft.AspNet.OData.Shared/ODataEdmAPIHandlerFactory.cs
  src/Microsoft.AspNet.OData.Shared/ODataIdResolver.cs
  src/Microsoft.AspNet.OData.Shared/Routing/ODataPath.cs
  src/Microsoft.AspNet.OData/GlobalSuppressions.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkInsertController.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/DeltaSetOfTTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/EdmChangedObjectCollectionTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Deserialization/ODataResourceDeserializerTests.cs
Labels: Medium

#2621 Update ODL version to Latest 7.10 in WebAPi projects
  samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
  samples/AspNetODataSample.Web/Web.config
  samples/AspNetODataSample.Web/packages.config
  src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
  src/Microsoft.AspNet.OData/packages.config
  src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/App.config
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Routing/DefaultODataPathHandlerTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
  test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj
Labels: Medium

#2523 Fix AmbiguousMatchException
  src/Microsoft.AspNet.OData.Shared/Query/Expressions/SelectExpandBinder.cs
  src/Microsoft.AspNet.OData.Shared/TypeHelper.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Expressions/SelectExpandBinderTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/TypeHelperTest.cs
Labels: Medium

#2626 Support $id references across entire batch
  src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs
  src/Microsoft.AspNet.OData.Shared/Formatter/Deserialization/ODataEntityReferenceLinkDeserializer.cs
  src/Microsoft.AspNet.OData/Batch/ChangeSetRequestItem.cs
  src/Microsoft.AspNet.OData/Batch/DefaultODataBatchHandler.cs
  src/Microsoft.AspNet.OData/Batch/ODataBatchHttpRequestMessageExtensions.cs
  src/Microsoft.AspNet.OData/Batch/ODataBatchReaderExtensions.cs
  src/Microsoft.AspNet.OData/Batch/ODataBatchRequestItem.cs
  src/Microsoft.AspNet.OData/Batch/OperationRequestItem.cs
  src/Microsoft.AspNet.OData/Batch/UnbufferedODataBatchHandler.cs
  src/Microsoft.AspNetCore.OData/Batch/ChangeSetRequestItem.cs
  src/Microsoft.AspNetCore.OData/Batch/DefaultODataBatchHandler.cs
  src/Microsoft.AspNetCore.OData/Batch/ODataBatchReaderExtensions.cs
  src/Microsoft.AspNetCore.OData/Batch/ODataBatchRequestItem.cs
  src/Microsoft.AspNetCore.OData/Batch/OperationRequestItem.cs
  src/Microsoft.AspNetCore.OData/Batch/UnbufferedODataBatchHandler.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Batch/Tests/DataServicesClient/DefaultODataBatchHandlerTests.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Batch/Tests/DataServicesClient/UnbufferedODataBatchHandlerTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore3x.OData.PublicApi.bsl
Labels: Extra Large

#2601 Update Patch to Return TStructuralType and Handle Patch for Derived Complex type
  src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ComplexTypeInheritance/ComplexTypeInheritanceControllers.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ComplexTypeInheritance/ComplexTypeInheritanceTests.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Formatter/DeltaTests.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/OpenType/OpenTypeControllers.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/OpenType/TypedTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/DeltaTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/InheritanceTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore3x.OData.PublicApi.bsl
Labels: Medium

#2627 Update WebAPi version for 7.5.13 release
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/OpenType/TypedTest.cs
  tools/WebStack.versions.settings.targets
Labels: Extra Small
