Repository OData/WebApi, pull requests merged in 2023-06, with the labels that each got.

#2785 Server-side paging should not apply to collections of non-entity types
  src/Microsoft.AspNet.OData.Shared/Query/Expressions/SelectExpandBinder.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ServerSidePaging/ServerSidePagingControllers.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ServerSidePaging/ServerSidePagingDataModel.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ServerSidePaging/ServerSidePagingTests.cs
Labels: Medium

#2780 Check HandleNullPropagation in ProjectElement
  src/Microsoft.AspNet.OData.Shared/Query/Expressions/SelectExpandBinder.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/NavigationPropertyOnComplexType/SelectImprovementOnComplexTypeTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/ApplyQueryOptionTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Expressions/SelectExpandBinderTest.cs
Labels: Extra Small

#2763 support async method in api handlers
  src/Microsoft.AspNet.OData.Shared/DefaultODataAPIHandler.cs
  src/Microsoft.AspNet.OData.Shared/DeltaSetOfT.cs
  src/Microsoft.AspNet.OData.Shared/ODataAPIHandler.cs
  src/Microsoft.AspNet.OData.Shared/ODataAPIHandlerFactory.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/BulkOperation/EFTests/BulkOperationControllerEF.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/BulkOperation/EFTests/BulkOperationPatchHandlersEF.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/BulkOperation/EFTests/BulkOperationTestEF.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationPatchHandlers.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/DeltaSetOfTTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test/PublicApi/Microsoft.AspNet.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore3x.OData.PublicApi.bsl
Labels: Extra Large
