Repository OData/WebApi, pull requests merged in 2023-02, with the labels that each got.

#2744 Fixes #2737: Support getting navigation source for complex types
  src/Microsoft.AspNet.OData.Shared/Formatter/Deserialization/ODataResourceDeserializerHelpers.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/Deserialization/ODataResourceDeserializerTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Resources/ProductsCsdl.xml
Labels: Large

#2750 Bump version to 7.6.4
  tools/WebStack.versions.settings.targets
Labels: Extra Small

#2751 AutoExpand does not expand beyond non-default MaxExpansionDepth
  src/Microsoft.AspNet.OData.Shared/ODataQueryContext.cs
  src/Microsoft.AspNet.OData.Shared/Query/ODataQueryOptions.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/AutoExpand/AutoExpandController.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/AutoExpand/AutoExpandDataModel.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/AutoExpand/AutoExpandEdmModel.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/AutoExpand/AutoExpandTests.cs
Labels: Small
