Repository OData/WebApi, pull requests merged in 2023-11, with the labels that each got.

#2819 Update version to 7.7.3 and relax Asp.NET Package version to >5.2.2 since 5.3.0 was released recently
  tools/WebStack.versions.settings.targets
Labels: Extra Small

#2824 Fix failing build
  pipelines/common.yml
  samples/AspNetCoreODataSample.Web/AspNetCoreODataSample.Web.csproj
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/ODataFormatterTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/ODataMediaTypeFormattersTests.cs
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Abstraction/Endpoint/EndpointRouteBuilderFactory.cs
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Abstraction/Endpoint/MockEndpointRouteBuilder.cs
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Abstraction/FormatterTestHelper.cs
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Abstraction/ODataActionSelectorTestHelper.cs
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Abstraction/RoutingConfigurationFactory.cs
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Abstraction/ServerFactory.cs
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Extensions/ActionDescriptorExtensionsTest.cs
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Extensions/Endpoint/ODataEndpointLinkGeneratorTests.cs
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Extensions/Endpoint/ODataEndpointPatternTests.cs
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Extensions/Endpoint/ODataEndpointRouteValueTransformerTests.cs
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Extensions/Endpoint/ODataEndpointSelectorPolicyTests.cs
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/PublicApiTest.cs
Labels: Small

#2822 Fix issue with property names which differ from Clr property names
  src/Microsoft.AspNet.OData.Shared/ODataAPIHandler.cs
  src/Microsoft.AspNet.OData.Shared/Query/ExpandQueryBuilder.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationController.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationDataModel.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationEdmModel.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationPatchHandlers.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationTest.cs
Labels: Medium
