Repository OData/WebApi, pull requests merged in 2023-09, with the labels that each got.

#2796 Fix broken serialization for $select used in non-Edm scenarios
  src/Microsoft.AspNet.OData.Shared/Common/SRResources.Designer.cs
  src/Microsoft.AspNet.OData.Shared/Common/SRResources.resx
  src/Microsoft.AspNet.OData.Shared/Microsoft.AspNet.OData.Shared.projitems
  src/Microsoft.AspNet.OData.Shared/Query/Expressions/SelectExpandBinder.cs
  src/Microsoft.AspNet.OData.Shared/Query/Expressions/SelectExpandWrapperJsonConverter.cs
  src/Microsoft.AspNet.OData.Shared/Query/Expressions/SelectExpandWrapperOfT.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/NonEdm/NonEdmController.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/NonEdm/NonEdmDataModel.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/NonEdm/NonEdmTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Microsoft.AspNet.OData.Test.Shared.projitems
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/Expressions/SelectExpandWrapperJsonConverterTests.cs
Labels: Extra Large

#2803 Fix for auto-generated swagger missing $filter for EntitySet
  src/Microsoft.AspNet.OData.Shared/ODataSwaggerUtilities.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Swagger/SwaggerMetadataTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/ODataSwaggerConverterTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/ODataSwaggerUtilitiesTest.cs
Labels: Extra Small

#2804 Fix case-insensitive property matching
  src/Microsoft.AspNet.OData.Shared/Formatter/ODataInputFormatterHelper.cs
  src/Microsoft.AspNet.OData.Shared/Formatter/ODataModelBinderConverter.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/OpenType/TypedTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Routing/ODataRoutingTest.cs
Labels: Extra Small

#2807 enable write dynamic complex for delta entity and complex
  src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/ODataResourceSerializer.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/DeltaQueryTests/DeltaQueryTests.cs
Labels: Small

#2809 Declared properties read as untyped when lower camel case is enabled
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/LowerCamelCase/LowerCamelCaseController.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/LowerCamelCase/LowerCamelCaseDataModel.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/LowerCamelCase/LowerCamelCaseTest.cs
Labels: Extra Small
