Repository OData/WebApi, pull requests merged in 2023-04, with the labels that each got.

#2764 support writing datamodififcation exception message
  src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/ODataResourceValueSerializer.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationTest.cs
Labels: Extra Small

#2765 Make CreatedODataResult inherit from ObjectResult
  src/Microsoft.AspNetCore.OData/Results/CreatedODataResult.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/BulkOperation/BulkOperationController.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/BulkOperation/BulkOperationTest.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationController.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationTest.cs
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl
  test/UnitTest/Microsoft.AspNetCore.OData.Test/PublicApi/Microsoft.AspNetCore3x.OData.PublicApi.bsl
Labels: Small

#2736 Fix skiptoken paging issue when combined with $orderby involving nullable property
  src/Microsoft.AspNet.OData.Shared/Common/SRResources.Designer.cs
  src/Microsoft.AspNet.OData.Shared/Common/SRResources.resx
  src/Microsoft.AspNet.OData.Shared/Query/DefaultSkipTokenHandler.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ServerSidePaging/ServerSidePagingControllers.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ServerSidePaging/ServerSidePagingDataModel.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/ServerSidePaging/ServerSidePagingTests.cs
Labels: Extra Large

#2769 fix regression issue.
  src/Microsoft.AspNet.OData.Shared/Formatter/Serialization/ODataResourceSerializer.cs
Labels: Extra Small
