Repository OData/WebApi, pull requests merged in 2023-07, with the labels that each got.

#2795 Null check in GenerateExpandQueryStringInternal
  src/Microsoft.AspNet.OData.Shared/Query/ExpandQueryBuilder.cs
Labels: Extra Small

#2797 Add GenerateExpandQueryStringInternal nullCheck tests
  src/Microsoft.AspNet.OData.Shared/Query/ExpandQueryBuilder.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationController.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/BulkOperation/BulkOperationTest.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Query/ExpandQueryBuilderTest.cs
Labels: Extra Small

#2798 Upgrade version to v7.7.1 and update ODL version
  samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
  samples/AspNetODataSample.Web/packages.config
  src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
  src/Microsoft.AspNet.OData/packages.config
  src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
  test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
  test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj
  tools/WebStack.versions.settings.targets
Labels: Medium

#2800 Add SECURITY.md containing instructions for reporting security bugs
  README.md
  SECURITY.md
Labels: Extra Small

#2733 Not able to use cast in orderby clause
  src/Microsoft.AspNet.OData.Shared/Query/Validators/OrderByModelLimitationsValidator.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/QueryComposition/OrderByTests.cs
Labels: Small
