Repository OData/WebApi, pull requests merged in 2024-01, with the labels that each got.

#2829 fixes #2816: Set the response version to delta response and delta patch response
  src/Microsoft.AspNet.OData.Shared/Formatter/ODataOutputFormatterHelper.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/DeltaQueryTests/DeltaQueryTests.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Formatter/Untyped/UntypedDeltaSerializationTests.cs
Labels: Extra Small

#2827 Add support for IEEE754Compatible media type parameter
  src/Microsoft.AspNet.OData.Shared/Formatter/ODataMediaTypes.cs
  src/Microsoft.AspNetCore.OData/Formatter/ODataInputFormatterFactory.cs
  src/Microsoft.AspNetCore.OData/Formatter/ODataOutputFormatterFactory.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/MediaTypes/MediaTypesModels.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/MediaTypes/MediaTypesOrdersController.cs
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/MediaTypes/MediaTypesTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/ODataMediaTypeFormattersTests.cs
  test/UnitTest/Microsoft.AspNet.OData.Test.Shared/Formatter/ODataMediaTypesTest.cs
Labels: Extra Large

#2831 Update version to 7.7.4 and ODL Version
  samples/AspNetODataSample.Web/AspNetODataSample.Web.csproj
  samples/AspNetODataSample.Web/packages.config
  src/Microsoft.AspNet.OData/Microsoft.AspNet.OData.csproj
  src/Microsoft.AspNet.OData/packages.config
  src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/Microsoft.Test.E2E.AspNet.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNet/packages.config
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/Microsoft.Test.E2E.AspNetCore.OData.csproj
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore/packages.config
  test/E2ETest/Microsoft.Test.E2E.AspNet.OData/Build.AspNetCore3x/Microsoft.Test.E2E.AspNetCore3x.OData.csproj
  test/UnitTest/Microsoft.AspNet.OData.Test/Microsoft.AspNet.OData.Test.csproj
  test/UnitTest/Microsoft.AspNet.OData.Test/packages.config
  test/UnitTest/Microsoft.AspNetCore.OData.Test/Microsoft.AspNetCore.OData.Test.csproj
  tools/WebStack.versions.settings.targets
Labels: Medium
